### ISSUE TITLE
 chabokpush.Chabok is not a constructor

### ISSUE THREAD

**Issue by faridraad** [chabok-io/chabok-client-js#3]
سلام 
در راه اندازی وب پوش با این خطا مواجه میشوم
 chabokpush.Chabok is not a constructor

لازم به ذکره که محیط تستی است
قطعه کدی که اضافه کردم اینه
    <script src="https://unpkg.com/chabokpush@1.6.0/dist/chabokpush.min.js"></script>
 const auth = {
            appId: '9a*****************************',
            webKey: '7ba*****************************',
            devMode: true
        }
        const options = {
            webpush: {
                enabled: true,
                publicKey: 'BKm*******************************'
            },
            silent: false,
            realtime: false
        };
        const chabok = new chabokpush.Chabok(auth, options);

**Comment by farbod-s** [comment]
<div dir="rtl">
سلام روزبخیر
<br>
اگر امکان داره نمونه کدی که در اون به این مشکل  برخوردید رو بصورت کاملتری ارسال کنید عالی میشه تا من بتونم شرایطی که در اون به خطا خوردید رو شبیه‌سازی کنم. برای مثال یک فایل html که راه‌اندازی چابک رو انجام دادید و به این خطا خورده.
<br>
پیشنهاد می‌کنم راه‌اندازی چابک در <a href="https://github.com/chabok-io/chabok-client-js/blob/master/sample/index.html#L121-L157">پروژه نمونه</a> رو بررسی کنید.
<br>
ممنون
</div>

**Comment by faridraad** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <script src="Scripts/Drag/http _code.jquery.com_ui_1.8.20_jquery-ui.min.js"></script>
    <script src="https://unpkg.com/chabokpush@1.6.0/dist/chabokpush.min.js"></script>
    <script src="ChabokSDKWorker.js"></script>
    <script type="text/javascript">
        const auth = {
            appId: '9a9*********************',
            webKey: '7ba*****************',
            devMode: true
        }
        const options = {
            webpush: {
                enabled: true,
                publicKey: 'BKm******************************'
            },
            silent: false,
            realtime: false
        };
        const chabok = new chabokpush.Chabok(auth, options);
        //chabok.registerAsGuest();
    </script>

 
</head>
<body>
</body>
</html>

**Comment by faridraad** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "
http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <script src="https://unpkg.com/chabokpush@1.6.0/dist/chabokpush.min.js
"></script>
    <script src="ChabokSDKWorker.js"></script>

    <script type="text/javascript">


        const auth = {
            appId: '9a98dd6ce5fed509426997c84ff23f17a1174f47',
            webKey: '7bac5022797eadd1cbad9dd5b4a72f8c921bd351',
            devMode: true
        }
        const options = {
            webpush: {
                enabled: true,
                publicKey:
'BKm3zVVpW8ShLbRZfQpIDo0J8tFZ9uXLzeokkWAa_qv9dcqDwTjysfdKJpYVO0TzedbTjE3KQRQ7gIp76-1zYR0'
            },
            silent: false,
            realtime: false
        };
        const chabok = new chabokpush.Chabok(auth, options);
        //chabok.registerAsGuest();
    </script>


</head>
<body>
</body>
</html>

**Comment by farbod-s** [comment]
<div dir="rtl">
سلام روز بخیر
<br>
قطعه کدی که فرستادید بدون مشکل اجرا شد.
<br>
برای راه‌اندازی چابک از کلیدهای پروژه نمونه استفاده شده.
</div>
<br>

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <script src="https://unpkg.com/chabokpush@1.6.0/dist/chabokpush.min.js"></script>
        <!-- <script src="ChabokSDKWorker.js"></script> -->
        <script type="text/javascript">
            const auth = {
                appId: 'chabok-starter',
                webKey: '1b98c60220b7e07c76142ea0635f69fb0dba5d7d',
                devMode: true
            }
            const options = {
                webpush: {
                    enabled: true,
                    publicKey: 'BLbNRYGZ39Qx-qYrlenpoWArW4zNR6A5XG9ch0VrA8YbJDWMJeWV0hK25Qt75NMrjgP_GG07TBnJ8gNPnVPGkyg'
                },
                silent: false,
                realtime: false
            };
            const chabok = new chabokpush.Chabok(auth, options);
            chabok.registerAsGuest();
        </script>
    </head>
    <body>
    </body>
</html>
```

**Comment by faridraad** [comment]
صفحه ساده Html
هیچ پروژه خاصی نیست
به شما خطا نداد؟

**Comment by farbod-s** [comment]
<div dir="rtl">
خطایی تحت عنوان chabokpush.Chabok is not a constructor داده نشد.
<br>
اگر محیط توسعه رو به درستی انتخاب نکرده باشید، یا مقدار دامنه توی پنل درست تنظیم نشده باشه خطاهای دیگه‌ای داده میشه.
<br>
خطای شما مربوط به راه‌اندازی هست که با قطعه کدی که ارسال کردید مشکلی نبود و راه‌اندازی با موفقیت انجام شد.
<br>
لطفا <a href="https://doc.chabok.io/javascript/sdk-setup.html">مستندات</a> رو بررسی کنید تا موردی از قلم نیفتاده باشه
<br>
<br>
میتونید در محیط node تست خودتون رو انجام بدید
<br>
</div>

```bash
sudo npm install -g serve
```
<div dir="rtl">
داخل پوشه‌ای که فایلتون هست دستور زیر رو بزنید:
</div>

```bash
serve
```

<div dir="rtl">
داخل پنل از بخش تنظیمات گزینه دسترسی و توکن‌ها رو انتخاب کنید و دامنه وب‌سایت رو localhost قرار بدید
<br>
از طریق آدرس زیر صفحه رو مشاهده کنید:
</div>

```bash
localhost:5000
```
